//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Module { get; set; }
        public string UserID { get; set; }
        public string Event { get; set; }
        public string MemberID { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> Date_Time_UTC { get; set; }
    }
}
