//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> National_ID { get; set; }
        public Nullable<System.DateTime> Date_Check_Out { get; set; }
        public Nullable<System.DateTime> Date_Return { get; set; }
        public string ISBN { get; set; }
    }
}
